name: Publish docs to Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - wiki/**
    branches:
      - main

env:
  USER_TOKEN: ${{ secrets.GH_PAT }}
  USER_NAME: "GitHub Actions"
  USER_EMAIL: "open-morphs@users.noreply.github.com"
  OWNER: open-morphs
  REPOSITORY_NAME: open-morphs

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Add Wiki as a remote
        run: git remote add wiki https://$OWNER:$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki

      - name: Make sure to fetch remotes, unshallowed
        run: git fetch --unshallow origin

      - name: Mirror all commits to production Wiki remote.
        run: git push --force wiki main:master

