name: Update wiki
on:
  push:
    branches: ["main"]
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: shymega@users.noreply.github.com
          ACTION_NAME: Open Morphs (GitHub Actions)
          GH_PAT: ${{ secrets.GH_PAT }}
          OWNER: open-morphs
          REPO_NAME: open-morphs
          SKIP_MD: README.md
      
